#!/bin/bash

# SSHD設定スクリプト
# パスワード認証を無効化し、鍵認証のみを許可する
# /etc/ssh/sshd_config.d/ 配下に設定ファイルを作成

set -e

# スクリプトのディレクトリを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ログ関数を読み込み
source "${SCRIPT_DIR}/lib/logging.sh"

# SSHD設定ファイルのパス
SSHD_CONFIG_DIR="/etc/ssh/sshd_config.d"
SSHD_CONFIG_FILE="${SSHD_CONFIG_DIR}/99-security.conf"

log_info "Starting SSHD security configuration..."

# root権限チェック
if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root"
    exit 1
fi

# ロールバック関数
rollback_config() {
    log_error "Rolling back configuration..."
    if [ -f "$SSHD_CONFIG_FILE" ]; then
        rm -f "$SSHD_CONFIG_FILE"
        systemctl restart sshd || systemctl restart ssh
        log_info "Configuration file removed and SSH service restarted."
    else
        log_error "Configuration file not found!"
    fi
}

# sshd_config.d ディレクトリの存在確認
if [ ! -d "$SSHD_CONFIG_DIR" ]; then
    log_error "Directory ${SSHD_CONFIG_DIR} does not exist."
    log_error "Your SSH version may not support sshd_config.d."
    exit 1
fi

# 設定ファイルを作成
log_info "Creating SSHD configuration file at ${SSHD_CONFIG_FILE}..."

cat > "$SSHD_CONFIG_FILE" << 'EOF'
# SSHD Security Configuration
# Generated by ct-server-setup

# パスワード認証を無効化
PasswordAuthentication no

# キーボードインタラクティブ認証を無効化
KbdInteractiveAuthentication no

# 公開鍵認証を有効化
PubkeyAuthentication yes

# SSSD経由で公開鍵を取得
AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys
AuthorizedKeysCommandUser nobody
EOF

chmod 600 "$SSHD_CONFIG_FILE"

log_info "SSHD configuration file created:"
log_info "  - PasswordAuthentication: no"
log_info "  - KbdInteractiveAuthentication: no"
log_info "  - PubkeyAuthentication: yes"
log_info "  - AuthorizedKeysCommand: /usr/bin/sss_ssh_authorizedkeys"
log_info "  - AuthorizedKeysCommandUser: nobody"

# 設定ファイルの検証
log_info "Validating SSHD configuration..."
if ! sshd -t 2>&1; then
    log_error "SSHD configuration validation failed!"
    rollback_config
    exit 1
fi
log_info "SSHD configuration is valid."

# SSHDサービスの再起動
log_info "Restarting SSHD service..."

# sshdまたはsshサービス名を判定
if systemctl list-units --type=service | grep -q "sshd.service"; then
    SERVICE_NAME="sshd"
elif systemctl list-units --type=service | grep -q "ssh.service"; then
    SERVICE_NAME="ssh"
else
    log_error "SSHD service not found"
    rollback_config
    exit 1
fi

if ! systemctl restart "$SERVICE_NAME"; then
    log_error "Failed to restart SSHD service."
    rollback_config
    exit 1
fi

# サービスの状態を確認
if ! systemctl is-active --quiet "$SERVICE_NAME"; then
    log_error "SSHD service failed to start properly."
    rollback_config
    exit 1
fi

log_info "SSHD service (${SERVICE_NAME}) restarted successfully."
log_warn "WARNING: Password authentication is now disabled."
log_warn "Make sure you have SSH key access configured before disconnecting!"

log_info "SSHD security configuration completed successfully."
